config/routes.rb
Rails.application.routes.draw do
  # root :to => "students#index"

  get 'signup', to: 'users#new', as: 'signup'

  get 'login', to: 'sessions#new', as: 'login'

  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions

  resources :users

  resources :courses do
    member do
      get :roll
    end
  end

  resources :students do
    resources :awards

    member do
      get :courses
      post :course_add
      post :course_remove
    end
  end

  root :to => "students#index"
#
#   Prefix Verb   URI Pattern                                     Controller#Action
#   signup          GET    /signup(.:format)                               users#new
#    login          GET    /login(.:format)                                sessions#new
#   logout          GET    /logout(.:format)                               sessions#destroy
# sessions          GET    /sessions(.:format)                             sessions#index
#                   POST   /sessions(.:format)                             sessions#create
# new_session       GET    /sessions/new(.:format)                         sessions#new
# edit_session  GET    /sessions/:id/edit(.:format)                    sessions#edit
#  session      GET    /sessions/:id(.:format)                         sessions#show
#               PATCH  /sessions/:id(.:format)                         sessions#update
#               PUT    /sessions/:id(.:format)                         sessions#update
#               DELETE /sessions/:id(.:format)                         sessions#destroy
#    users      GET    /users(.:format)                                users#index
#               POST   /users(.:format)                                users#create
# new_user      GET    /users/new(.:format)                            users#new
# edit_user     GET    /users/:id/edit(.:format)                       users#edit
#     user      GET    /users/:id(.:format)                            users#show
#               PATCH  /users/:id(.:format)                            users#update
#               PUT    /users/:id(.:format)                            users#update
#               DELETE /users/:id(.:format)                            users#destroy
# roll_course   GET    /courses/:id/roll(.:format)                     courses#roll
#  courses      GET    /courses(.:format)                              courses#index
#               POST   /courses(.:format)                              courses#create
# new_course    GET    /courses/new(.:format)                          courses#new
# edit_course   GET    /courses/:id/edit(.:format)                     courses#edit
#   course      GET    /courses/:id(.:format)                          courses#show
#               PATCH  /courses/:id(.:format)                          courses#update
#               PUT    /courses/:id(.:format)                          courses#update
#               DELETE /courses/:id(.:format)                          courses#destroy
# student_awards GET    /students/:student_id/awards(.:format)          awards#index
#               POST   /students/:student_id/awards(.:format)          awards#create
# new_student_award GET    /students/:student_id/awards/new(.:format)      awards#new
# edit_student_award GET    /students/:student_id/awards/:id/edit(.:format) awards#edit
# student_award GET    /students/:student_id/awards/:id(.:format)      awards#show
#          PATCH  /students/:student_id/awards/:id(.:format)      awards#update
#          PUT    /students/:student_id/awards/:id(.:format)      awards#update
#          DELETE /students/:student_id/awards/:id(.:format)      awards#destroy
# courses_student GET    /students/:id/courses(.:format)                 students#courses
# course_add_student POST   /students/:id/course_add(.:format)              students#course_add
# course_remove_student POST   /students/:id/course_remove(.:format)           students#course_remove
# students GET    /students(.:format)                             students#index
#          POST   /students(.:format)                             students#create
# new_student GET    /students/new(.:format)                         students#new
# edit_student GET    /students/:id/edit(.:format)                    students#edit
#  student GET    /students/:id(.:format)                         students#show
#          PATCH  /students/:id(.:format)                         students#update
#          PUT    /students/:id(.:format)                         students#update
#          DELETE /students/:id(.:format)                         students#destroy
#     root GET    /
end

app/models/student.rb
class Student < ApplicationRecord
  # a student can have many awards
  has_many :awards, dependent: :destroy
  has_and_belongs_to_many :courses
  validates_presence_of :date_of_birth, :start_date

  def name
    given_name + " " + family_name
  end

  def enrolled_in?(course)
    self.courses.include?(course)
  end

  def unenrolled_courses
    Course.all - self.courses
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  before_action :is_admin, only: [:new, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)
    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # determines which courses belong to the current student
  def courses
    @student = Student.find(params[:id])
    @courses = @student.courses
  end

  # gets student_id and adds the student to that course
  # POST /students/1/course_add?course_id=2
  # no query string but a notation for parameters
  def course_add

    #Convert ids from routing to objects
    @student = Student.find(params[:id])
    @course = Course.find(params[:course])

    unless @student.enrolled_in?(@course)
      # add course to llist using << operator
      @student.courses << @course
      flash[:notice] = 'Student was successfully enrolled.'
    else
      flash[:error] = 'Student was already enrolled.'
    end

    redirect_to action: "courses", id: @student
  end

  # used to unenroll a student from the course
  def course_remove
    # convert id's fro routing to an object
    @student = Student.find(params[:id])

    # get list of courses to remove from query string
    course_ids = params[:courses]

    unless course_ids.blank?
      course_ids.each do |course_id|
        course = Course.find(course_id)
        if @student.enrolled_in?(course)
          logger.info 'Removing student from course #{course.id}.'
          @student.courses.delete(course)
          flash[:notice] = 'Course was successfully deleted.'
        end
      end
    end
    redirect_to action: "courses", id: @student
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:given_name, :middle_name, :family_name, :date_of_birth, :grade_point_average, :start_date)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(student) do |f| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :given_name %>
    <%= f.text_field :given_name %>
  </div>

  <div class="field">
    <%= f.label :middle_name %>
    <%= f.text_field :middle_name %>
  </div>

  <div class="field">
    <%= f.label :family_name %>
    <%= f.text_field :family_name %>
  </div>

  <div class="field">
    <%= f.label :date_of_birth %>
    <%= f.date_select :date_of_birth %>
  </div>

  <div class="field">
    <%= f.label :grade_point_average %>
    <%= f.text_field :grade_point_average %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/courses.html.erb
<h1><%= @student.name %>'s courses</h1>

<!-- The first form appears if the student is already enrolled in any courses, -->
<!-- allowing the user to remove them from those courses. -->
<!-- This connects to the course_remove controller method -->

<% if @courses.length > 0 %>
  <%= form_tag(course_remove_student_path(@student)) do %>
  <table>
    <thead>
      <tr>
        <th>Course</th>
        <th>Remove?</th>
      </tr>
    </thead>

    <tbody>
      <% for course in @courses do %>
        <tr>
          <td><%= course.name %></td>
          <td><%= check_box_tag "courses[]", course.id %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br />
  <%=  submit_tag 'Remove checked courses' %>
  <% end %>
  <% else %>
    <p> Not enrolled in any courses yet.</p>
  <% end %>
  <br />
  <br />
  <!-- The second form appears if there are courses that the student hasn’t -->
  <!-- yet enrolled in. -->
  <!-- This connects to the course_add controller method -->

  <% if @student.courses.count < Course.count then %>
    <%= form_tag(course_add_student_path(@student)) do %>
      <%= select_tag(:course, options_from_collection_for_select(@student.unenrolled_courses, :id, :name)) %>
      <%= submit_tag 'Enroll' %>
    <% end %>
  <% else %>
    <p><%= @student.name %> is enrolled in every course.</p>
  <% end %>

  <p><%= link_to "Back", @student %></p>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Student Name</th>
      <th>Date of birth</th>
      <th>GPA</th>
      <th>Start date</th>
      <th>Courses</th>
      <th>Awards</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td class="name">
          <%= student.given_name %>
          <%= student.middle_name %>r
          <%= student.family_name %>
        </td>
        <td><%= student.date_of_birth %></td>
        <td><%= student.grade_point_average %></td>
        <td><%= student.start_date %></td>
        <td><%= student.courses.count %></td>

        <td><%= student.awards.count %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Awards', student_awards_path(student) %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Edit', edit_student_path(student) %></td>
          <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }, class: :destroy %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.admin? %>
  <%= link_to 'New Student', new_student_path %>
<% end %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Basic Information</h3>
<p>
  <strong>Given name:</strong>
  <%= @student.given_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @student.middle_name %>
</p>

<p>
  <strong>Family name:</strong>
  <%= @student.family_name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @student.date_of_birth %>
</p>

<p>
  <strong>Grade point average:</strong>
  <%= @student.grade_point_average %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @student.start_date %>
</p>

<h3>Courses</h3>
<p>
  <% if !@student.courses.empty? %>
      <%= @student.courses.collect {|c| link_to(c.name, c)}.join(", ").html_safe %>
  <% else %>
    Not enrolled on any courses yet.
  <% end %>
</p>
<h3>Awards</h3>
<table>
  <tr>
    <th>Name</th>
    <th>Year</th>
    <th>Student</th>
  </tr>

<% @student.awards.each do |award| %>
  <tr>
    <td><%= award.name %></td>
    <td><%= award.year %></td>
    <td><%= award.student.name %></td>
  </tr>
<% end %>
</table>

<% if current_user.admin? %>
  <%= link_to 'Edit', edit_student_path(@student) %> |
  <%= link_to 'Courses', courses_student_path(@student) %> |
<% end %>

<%= link_to 'Awards', student_awards_path(@student)%> |
<%= link_to 'Back', students_path %>