config/routes.rb
Rails.application.routes.draw do
  # root :to => "students#index"

  get 'signup', to: 'users#new', as: 'signup'

  get 'login', to: 'sessions#new', as: 'login'

  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions

  resources :users

  resources :courses do
    member do
      get :roll
    end
  end

  resources :students do
    resources :awards

    member do
      get :courses
      post :course_add
      post :course_remove
    end
  end

  root :to => "students#index"
#
#   Prefix Verb   URI Pattern                                     Controller#Action
#   signup          GET    /signup(.:format)                               users#new
#    login          GET    /login(.:format)                                sessions#new
#   logout          GET    /logout(.:format)                               sessions#destroy
# sessions          GET    /sessions(.:format)                             sessions#index
#                   POST   /sessions(.:format)                             sessions#create
# new_session       GET    /sessions/new(.:format)                         sessions#new
# edit_session  GET    /sessions/:id/edit(.:format)                    sessions#edit
#  session      GET    /sessions/:id(.:format)                         sessions#show
#               PATCH  /sessions/:id(.:format)                         sessions#update
#               PUT    /sessions/:id(.:format)                         sessions#update
#               DELETE /sessions/:id(.:format)                         sessions#destroy
#    users      GET    /users(.:format)                                users#index
#               POST   /users(.:format)                                users#create
# new_user      GET    /users/new(.:format)                            users#new
# edit_user     GET    /users/:id/edit(.:format)                       users#edit
#     user      GET    /users/:id(.:format)                            users#show
#               PATCH  /users/:id(.:format)                            users#update
#               PUT    /users/:id(.:format)                            users#update
#               DELETE /users/:id(.:format)                            users#destroy
# roll_course   GET    /courses/:id/roll(.:format)                     courses#roll
#  courses      GET    /courses(.:format)                              courses#index
#               POST   /courses(.:format)                              courses#create
# new_course    GET    /courses/new(.:format)                          courses#new
# edit_course   GET    /courses/:id/edit(.:format)                     courses#edit
#   course      GET    /courses/:id(.:format)                          courses#show
#               PATCH  /courses/:id(.:format)                          courses#update
#               PUT    /courses/:id(.:format)                          courses#update
#               DELETE /courses/:id(.:format)                          courses#destroy
# student_awards GET    /students/:student_id/awards(.:format)          awards#index
#               POST   /students/:student_id/awards(.:format)          awards#create
# new_student_award GET    /students/:student_id/awards/new(.:format)      awards#new
# edit_student_award GET    /students/:student_id/awards/:id/edit(.:format) awards#edit
# student_award GET    /students/:student_id/awards/:id(.:format)      awards#show
#          PATCH  /students/:student_id/awards/:id(.:format)      awards#update
#          PUT    /students/:student_id/awards/:id(.:format)      awards#update
#          DELETE /students/:student_id/awards/:id(.:format)      awards#destroy
# courses_student GET    /students/:id/courses(.:format)                 students#courses
# course_add_student POST   /students/:id/course_add(.:format)              students#course_add
# course_remove_student POST   /students/:id/course_remove(.:format)           students#course_remove
# students GET    /students(.:format)                             students#index
#          POST   /students(.:format)                             students#create
# new_student GET    /students/new(.:format)                         students#new
# edit_student GET    /students/:id/edit(.:format)                    students#edit
#  student GET    /students/:id(.:format)                         students#show
#          PATCH  /students/:id(.:format)                         students#update
#          PUT    /students/:id(.:format)                         students#update
#          DELETE /students/:id(.:format)                         students#destroy
#     root GET    /
end

app/models/award.rb
class Award < ApplicationRecord
  # an award can be linked to a student, via a student_id (foreign_key)
  belongs_to :student
  validates_associated :student

  validates_presence_of :name, :year

 # award can be given only once a year
  validates_uniqueness_of :name, scope: :year

 # award scheme was started in 1980
  validates_inclusion_of :year, in: (1980..Date.today.year)
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  before_action :get_student
  before_action :set_award, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /awards
  # GET /awards.json
  def index
    @awards = @student.awards
  end

  # GET /awards/1
  # GET /awards/1.json
  def show
    @award = @student.awards.find(params[:id])
  end

  # GET /awards/new
  def new
    @award = @student.awards.build
  end

  # GET /awards/1/edit
  def edit
    @award = @student.awards.find(params[:id])
  end

  # POST /awards
  # POST /awards.json
  def create
    @award = @student.awards.build(award_params)

    respond_to do |format|
      if @award.save
        format.html { redirect_to student_awards_url(@student), notice: 'Award was successfully created.' }
        format.json { render :show, status: :created, location: @award }
      else
        format.html { render :new }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /awards/1
  # PATCH/PUT /awards/1.json
  def update
    @award = @student.awards.find(params[:id])

    respond_to do |format|
      if @award.update(award_params)
        format.html { redirect_to student_awards_url(@student), notice: 'Award was successfully updated.' }
        format.json { render :show, status: :ok, location: @award }
      else
        format.html { render :edit }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /awards/1
  # DELETE /awards/1.json
  def destroy
    @award = @student.awards.find(params[:id])

    @award.destroy
    respond_to do |format|
      format.html { redirect_to  (student_awards_path(@student)), notice: 'Award was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def get_student
      @student = Student.find(params[:student_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_award
      @award = @student.awards.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def award_params
      params.require(:award).permit(:name, :year, :student_id)
    end

end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/views/awards/_form.html.erb
<%= form_for([ @student, award ]) do |f| %>
  <% if award.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(award.errors.count, "error") %> prohibited this award from being saved:</h2>

      <ul>
      <% award.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.number_field :year %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/awards/edit.html.erb
<h1>Editing Award for <%= @student.name %></h1>

<%= render 'form', award: @award %>

<%= link_to 'Show', [ @student, @award ] %> |
<%= link_to 'Back', student_awards_path(@student) %>

app/views/awards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Awards for <%= @student.name %></h1>

<% if !@student.awards.empty? %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Year</th>
        <th>Student</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @awards.each do |award| %>
        <tr>
          <td><%= award.name %></td>
          <td><%= award.year %></td>
          <td><%= award.student.name %></td>
          <td><%= link_to 'Show', [ @student, award ] %></td>
          <% if current_user.admin? %>
            <td><%= link_to 'Edit', edit_student_award_path( @student, award )%></td>
            <td><%= link_to 'Destroy', [ @student, award ], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
<% else %>
  <p><%= @student.given_name %> hasn't won any awards yet.</p>
<% end %>

<% if current_user.admin? %>
  <%= link_to 'New Award', new_student_award_path(@student) %>
<% end %>
<%= link_to 'Back', @student %>

app/views/awards/new.html.erb
<h1>New Award for <%= @student.name %></h1>

<%= render 'form', award: @award %>

<%= link_to 'Back', student_awards_path(@student) %>

app/views/awards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @award.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @award.year %>
</p>

<p>
  <strong>Student:</strong>
  <%= @award.student.name %>
</p>

<% if current_user.admin? %>
  <%= link_to 'Edit', edit_student_award_path(@student, @award) %> |
<% end %>
<%= link_to 'Back', student_awards_path(@student) %>