config/routes.rb
Rails.application.routes.draw do
  # root :to => "students#index"

  get 'signup', to: 'users#new', as: 'signup'

  get 'login', to: 'sessions#new', as: 'login'

  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions

  resources :users

  resources :courses do
    member do
      get :roll
    end
  end

  resources :students do
    resources :awards

    member do
      get :courses
      post :course_add
      post :course_remove
    end
  end

  root :to => "students#index"
#
#   Prefix Verb   URI Pattern                                     Controller#Action
#   signup          GET    /signup(.:format)                               users#new
#    login          GET    /login(.:format)                                sessions#new
#   logout          GET    /logout(.:format)                               sessions#destroy
# sessions          GET    /sessions(.:format)                             sessions#index
#                   POST   /sessions(.:format)                             sessions#create
# new_session       GET    /sessions/new(.:format)                         sessions#new
# edit_session  GET    /sessions/:id/edit(.:format)                    sessions#edit
#  session      GET    /sessions/:id(.:format)                         sessions#show
#               PATCH  /sessions/:id(.:format)                         sessions#update
#               PUT    /sessions/:id(.:format)                         sessions#update
#               DELETE /sessions/:id(.:format)                         sessions#destroy
#    users      GET    /users(.:format)                                users#index
#               POST   /users(.:format)                                users#create
# new_user      GET    /users/new(.:format)                            users#new
# edit_user     GET    /users/:id/edit(.:format)                       users#edit
#     user      GET    /users/:id(.:format)                            users#show
#               PATCH  /users/:id(.:format)                            users#update
#               PUT    /users/:id(.:format)                            users#update
#               DELETE /users/:id(.:format)                            users#destroy
# roll_course   GET    /courses/:id/roll(.:format)                     courses#roll
#  courses      GET    /courses(.:format)                              courses#index
#               POST   /courses(.:format)                              courses#create
# new_course    GET    /courses/new(.:format)                          courses#new
# edit_course   GET    /courses/:id/edit(.:format)                     courses#edit
#   course      GET    /courses/:id(.:format)                          courses#show
#               PATCH  /courses/:id(.:format)                          courses#update
#               PUT    /courses/:id(.:format)                          courses#update
#               DELETE /courses/:id(.:format)                          courses#destroy
# student_awards GET    /students/:student_id/awards(.:format)          awards#index
#               POST   /students/:student_id/awards(.:format)          awards#create
# new_student_award GET    /students/:student_id/awards/new(.:format)      awards#new
# edit_student_award GET    /students/:student_id/awards/:id/edit(.:format) awards#edit
# student_award GET    /students/:student_id/awards/:id(.:format)      awards#show
#          PATCH  /students/:student_id/awards/:id(.:format)      awards#update
#          PUT    /students/:student_id/awards/:id(.:format)      awards#update
#          DELETE /students/:student_id/awards/:id(.:format)      awards#destroy
# courses_student GET    /students/:id/courses(.:format)                 students#courses
# course_add_student POST   /students/:id/course_add(.:format)              students#course_add
# course_remove_student POST   /students/:id/course_remove(.:format)           students#course_remove
# students GET    /students(.:format)                             students#index
#          POST   /students(.:format)                             students#create
# new_student GET    /students/new(.:format)                         students#new
# edit_student GET    /students/:id/edit(.:format)                    students#edit
#  student GET    /students/:id(.:format)                         students#show
#          PATCH  /students/:id(.:format)                         students#update
#          PUT    /students/:id(.:format)                         students#update
#          DELETE /students/:id(.:format)                         students#destroy
#     root GET    /
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # lists the students enrolled in the course
  def roll
    @course = Course.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Enrolled</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.students.count %></td>
        <td><%= link_to 'Show', course %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Edit', edit_course_path(course) %></td>
          <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.admin? %>
  <%= link_to 'New Course', new_course_path %>
<% end %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/roll.html.erb
<!-- This generates a roll call list through the connections from courses to students -->
<h1> Roll for <%= @course.name %></h1>

<% if @course.students.count > 0 %>
  <table>
    <thead>
      <tr>
        <th>Student</th>
        <th>GPA</th>
      </tr>
    </thead>

    <tbody>
      <% @course.students.each do |student| %>
        <tr>
          <td><%= link_to student.name, student %></td>
          <td><%= student.grade_point_average %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No students are enrolled</p>
<% end %>

<p><%= link_to "Back", @course %></p>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<% if current_user.admin? %>
  <%= link_to 'Edit', edit_course_path(@course) %> |
<% end %>
<%= link_to 'Roll', roll_course_path %> |
<%= link_to 'Back', courses_path %>